(()=>{
  const REP='#c62828';
  function ensureStyle(){if(document.getElementById('safe-ui-patches-v2'))return;const s=document.createElement('style');s.id='safe-ui-patches-v2';s.textContent=`#page-senate .map-wrap svg{transform:scale(1.14)!important;transform-origin:center center!important}@media(max-width:650px){#page-senate .map-wrap svg{transform:scale(1.08)!important}}#page-betting .live-kalshi-title{display:flex!important;align-items:center!important}#page-betting .live-kalshi-dot{display:inline-block!important;width:10px!important;height:10px!important;border-radius:50%!important;background:#e32636!important;margin-right:9px!important;animation:kalshiPulseSafe 1.15s ease-in-out infinite!important}@keyframes kalshiPulseSafe{0%,100%{opacity:1}50%{opacity:.32}}@media(max-width:760px){#page-senate [data-safe-republican-red="1"]{color:${REP}!important;fill:${REP}!important;border-color:${REP}!important}}`;document.head.appendChild(s);}
  function kalshi(){const root=document.getElementById('page-betting');if(!root)return;const h=[...root.querySelectorAll('h1,h2,h3')].find(el=>/^(live\s+)?kalshi\s+senate\s+odds$/i.test((el.textContent||'').replace(/\s+/g,' ').trim()));if(!h)return;h.classList.add('live-kalshi-title');if(!h.querySelector('.live-kalshi-dot')){h.textContent='';const d=document.createElement('span');d.className='live-kalshi-dot';h.append(d,document.createTextNode('Live Kalshi Senate Odds'));}}
  function isR(v){v=String(v||'').toLowerCase();return v==='r'||v==='rep'||v==='gop'||v.includes('republican');}
  function republicans(){if(!matchMedia('(max-width:760px)').matches)return;const root=document.getElementById('page-senate');if(!root)return;root.querySelectorAll('.candidate-line').forEach(line=>{const p=line.querySelector('.candidate-party');if(!p||!isR(p.textContent))return;line.querySelectorAll('.candidate-name,.candidate-party,.candidate-metrics b,.candidate-metrics strong').forEach(el=>{el.dataset.safeRepublicanRed='1';el.style.setProperty('color',REP,'important');});});}
  function school(){const root=document.getElementById('page-about');if(!root||document.getElementById('aboutSchool'))return;const strip=root.querySelector('.about-stat-strip');if(!strip)return;const s=document.createElement('section');s.id='aboutSchool';s.style.cssText='margin:14px 0 18px;padding:16px 18px;border:1px solid #d9dee7;border-radius:16px;background:#fff;display:flex;align-items:center;gap:18px;box-shadow:0 7px 22px rgba(20,34,53,.055)';s.innerHTML='<div style="font-size:34px">🌲</div><div><div style="font-size:9px;font-weight:950;letter-spacing:1.4px;color:#d92732;text-transform:uppercase">School</div><h3 style="margin:3px 0 0;font-family:Georgia,serif;font-size:21px;color:#17263d">Redwood High School</h3><p style="margin:4px 0 0;font-size:12px;color:#66758a">Larkspur, California</p></div>';strip.insertAdjacentElement('afterend',s);}
  function apply(){ensureStyle();kalshi();republicans();school();}
  apply();new MutationObserver(()=>requestAnimationFrame(apply)).observe(document.body,{childList:true,subtree:true,characterData:true});window.addEventListener('pageshow',apply);window.addEventListener('resize',apply);
})();